version: '3'
services:
  app:
    image: ineuron:latest
    environment:
      - MONGO_URL=mongodb://mongo:27017/ineuron
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
    ports:
      - '27018:27017'
